### ISSUE TITLE
Did you compare the Number of Parameters for Basic CNN model and the Deep CNN model?

### ISSUE THREAD

**Issue by yupengyanghuhu** [yupengyanghuhu/CSF_Final_Project#13]

**Comment by deenhuang** [comment]
Yeah. After a convolution layer, it is common to add a pooling layer in between CNN layers. The function of pooling is to continuously reduce the dimensionality to reduce the number of parameters and computation in the network. This shortens the training time and controls overfitting. Actually, the deep cnn yields better accuracy because, it has more max pooling layers and fewer parameters/features to train on, helps in dimensionality reduction.
